name: Render and Split Videos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  render:
    name: Render and Split Videos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install ffmpeg -y

      - name: Install dependencies
        run: npm install

      # Render the entire video
      - name: Render full video
        run: npx remotion render src/index.js demo out/full-video.mp4

      # Split the video into 8 parts using FFmpeg and frame numbers
      - name: Split video into clips by frames
        run: |
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,0,449)',setpts=N/FRAME_RATE/TB" -af "aselect='between(n,0,449)',asetpts=N/SR/TB" out/video1.mp4
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,450,899)',setpts=N/FRAME_RATE/TB" -af "aselect='between(n,450,899)',asetpts=N/SR/TB" out/video2.mp4
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,900,1349)',setpts=N/FRAME_RATE/TB" -af "aselect='between(n,900,1349)',asetpts=N/SR/TB" out/video3.mp4
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,1350,1799)',setpts=N/FRAME_RATE/TB" -af "aselect='between(n,1350,1799)',asetpts=N/SR/TB" out/video4.mp4
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,1800,2249)',setpts=N/FRAME_RATE/TB" -af "aselect='between(n,1800,2249)',asetpts=N/SR/TB" out/video5.mp4
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,2250,2699)',setpts=N/FRAME_RATE/TB" -af "aselect='between(n,2250,2699)',asetpts=N/SR/TB" out/video6.mp4
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,2700,3149)',setpts=N/FRAME_RATE/TB" -af "aselect='between(n,2700,3149)',asetpts=N/SR/TB" out/video7.mp4
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,3150,3599)',setpts=N/FRAME_RATE/TB" -af "aselect='between(n,3150,3599)',asetpts=N/SR/TB" out/video8.mp4

      - name: Upload rendered videos
        uses: actions/upload-artifact@v3
        with:
          name: rendered-videos-${{ github.run_number }}
          path: |
            out/video1.mp4
            out/video2.mp4
            out/video3.mp4
            out/video4.mp4
            out/video5.mp4
            out/video6.mp4
            out/video7.mp4
            out/video8.mp4