name: Render video

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Match the Node.js version for Remotion

      # Install FFmpeg
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install ffmpeg -y

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Render the video
      - name: Render video
        run: npx remotion render src/index.js demo out/video.mp4

      # Upload the rendered video as an artifact
      - name: Upload rendered video
        uses: actions/upload-artifact@v3
        with:
          name: rendered-video
          path: out/video.mp4
