name: Render videos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  render:
    name: Render videos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install ffmpeg -y

      - name: Install dependencies
        run: npm install

      # Render videos
      - name: Render video 1
        run: npx remotion render src/index.js demo out/video1.mp4 --frames=0-449

      - name: Render video 2
        run: npx remotion render src/index.js demo out/video2.mp4 --frames=450-899

      - name: Render video 3
        run: npx remotion render src/index.js demo out/video3.mp4 --frames=900-1349

      - name: Render video 4
        run: npx remotion render src/index.js demo out/video4.mp4 --frames=1350-1799

      - name: Render video 5
        run: npx remotion render src/index.js demo out/video5.mp4 --frames=1800-2249

      - name: Render video 6
        run: npx remotion render src/index.js demo out/video6.mp4 --frames=2250-2699

      - name: Render video 7
        run: npx remotion render src/index.js demo out/video7.mp4 --frames=2700-3149

      - name: Render video 8
        run: npx remotion render src/index.js demo out/video8.mp4 --frames=3150-3599

      - name: Upload rendered videos
        uses: actions/upload-artifact@v3
        with:
          name: rendered-videos-${{ github.run_number }}
          path: |
            out/video1.mp4
            out/video2.mp4
            out/video3.mp4
            out/video4.mp4
            out/video5.mp4
            out/video6.mp4
            out/video7.mp4
            out/video8.mp4
