name: Render video

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch
  workflow_dispatch: # Allows manual trigger

jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install FFmpeg
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Render the video
      - name: Render video
        run: npx remotion render src/video.jsx out/video.mp4

      # Step 6: Upload the rendered video
      - name: Upload video artifact
        uses: actions/upload-artifact@v3
        with:
          name: rendered-video
          path: out/video.mp4
