name: Render videos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  render:
    name: Render videos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install ffmpeg -y

      - name: Install dependencies
        run: npm install

      # Render the videos (each on a separate line)
      - name: Render videos
        run: |
          npx remotion render src/index.js demo out/video1.mp4 --frames=0-269
          npx remotion render src/index.js demo out/video2.mp4 --frames=270-539
          npx remotion render src/index.js demo out/video3.mp4 --frames=540-809
          npx remotion render src/index.js demo out/video4.mp4 --frames=810-1079
          npx remotion render src/index.js demo out/video5.mp4 --frames=1080-1349
          npx remotion render src/index.js demo out/video6.mp4 --frames=1350-1619
          npx remotion render src/index.js demo out/video7.mp4 --frames=1620-1889
          npx remotion render src/index.js demo out/video8.mp4 --frames=1890-2159
          npx remotion render src/index.js demo out/video9.mp4 --frames=2160-2429

      - name: Upload rendered videos
        uses: actions/upload-artifact@v3
        with:
          name: rendered-videos-${{ github.run_number }}
          path: |
            out/video1.mp4
            out/video2.mp4
            out/video3.mp4
            out/video4.mp4
            out/video5.mp4
            out/video6.mp4
            out/video7.mp4
            out/video8.mp4
            out/video9.mp4
