name: Render and Split Videos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  render:
    name: Render and Split Videos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install FFmpeg and ffprobe
        run: |
          sudo apt update
          sudo apt install ffmpeg -y

      - name: Install dependencies
        run: npm install

      # Render the entire video
      - name: Render full video
        run: npx remotion render src/index.js demo out/full-video.mp4

      # Get the video frame rate using ffprobe
      - name: Get video frame rate
        id: get_frame_rate
        run: |
          FRAME_RATE=$(ffprobe -v error -select_streams v:0 -show_entries stream=r_frame_rate -of default=noprint_wrappers=1:nokey=1 out/full-video.mp4)
          echo "::set-output name=frame_rate::$FRAME_RATE"

      # Split the video into 8 parts using FFmpeg and frame numbers
      - name: Split video into clips by frames
        env:
          FRAME_RATE: ${{ steps.get_frame_rate.outputs.frame_rate }}
        run: |
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,0,449)',setpts=N/${FRAME_RATE}*TB" -filter:a "aselect='between(n,0,449)',asetpts=N/SR/TB" -c:v libx264 -crf 18 -preset veryslow -c:a aac -b:a 192k out/video1.mp4
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,510,959)',setpts=N/${FRAME_RATE}*TB" -filter:a "aselect='between(n,510,959)',asetpts=N/SR/TB" -c:v libx264 -crf 18 -preset veryslow -c:a aac -b:a 192k out/video2.mp4
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,1020,1469)',setpts=N/${FRAME_RATE}*TB" -filter:a "aselect='between(n,1020,1469)',asetpts=N/SR/TB" -c:v libx264 -crf 18 -preset veryslow -c:a aac -b:a 192k out/video3.mp4
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,1530,1979)',setpts=N/${FRAME_RATE}*TB" -filter:a "aselect='between(n,1530,1979)',asetpts=N/SR/TB" -c:v libx264 -crf 18 -preset veryslow -c:a aac -b:a 192k out/video4.mp4
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,2040,2489)',setpts=N/${FRAME_RATE}*TB" -filter:a "aselect='between(n,2040,2489)',asetpts=N/SR/TB" -c:v libx264 -crf 18 -preset veryslow -c:a aac -b:a 192k out/video5.mp4
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,2550,2999)',setpts=N/${FRAME_RATE}*TB" -filter:a "aselect='between(n,2550,2999)',asetpts=N/SR/TB" -c:v libx264 -crf 18 -preset veryslow -c:a aac -b:a 192k out/video6.mp4
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,3060,3509)',setpts=N/${FRAME_RATE}*TB" -filter:a "aselect='between(n,3060,3509)',asetpts=N/SR/TB" -c:v libx264 -crf 18 -preset veryslow -c:a aac -b:a 192k out/video7.mp4
          ffmpeg -i out/full-video.mp4 -filter:v "select='between(n,3570,4019)',setpts=N/${FRAME_RATE}*TB" -filter:a "aselect='between(n,3570,4019)',asetpts=N/SR/TB" -c:v libx264 -crf 18 -preset veryslow -c:a aac -b:a 192k out/video8.mp4

      - name: Upload rendered videos
        uses: actions/upload-artifact@v3
        with:
          name: rendered-videos-${{ github.run_number }}
          path: |
            out/video1.mp4
            out/video2.mp4
            out/video3.mp4
            out/video4.mp4
            out/video5.mp4
            out/video6.mp4
            out/video7.mp4
            out/video8.mp4